on:
  release:
    types: [published]

name: Release

jobs:
  upload-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw package -Dquarkus.package.type=uber-jar
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.name }} $(ls target/*-runner.jar)
  push-java-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-release-version
        shell: bash
        run: |
          appVersion=$(echo ${{ github.event.release.name }} | cut -d'v' -f 2)
          echo "version=$appVersion" >> "$GITHUB_OUPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.jvm
          push: true
          tags: lgdd/liferay-starter:latest-jvm,lgdd/liferay-starter:${{ steps.get-release-version.outputs.version }}-jvm
  push-native-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-release-version
        shell: bash
        run: |
          appVersion=$(echo ${{ github.event.release.name }} | cut -d'v' -f 2)
          echo "version=$appVersion" >> "$GITHUB_OUPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.native
          push: true
          tags: lgdd/liferay-starter:latest,lgdd/liferay-starter:${{ steps.get-release-version.outputs.version }}